apiVersion: v1
kind: Service
metadata:
  name: nestjs-service
  namespace: prueba-argo
  labels:
    app: nestjs-app
spec:
  selector:
    app: nestjs-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
